[project]
name = "xenforo-links-archive"
version = "0.1.0"
dependencies = [
    "fastapi>=0.115.6",
    "pydantic>=2.10.4",
    "rich>=13.9.4",
    "uvicorn>=0.34.0",
    "yarl>=1.18.3"
]
description = "Save URLs to a local database"
readme = "README.md"
requires-python = ">=3.12"

[dependency-groups]
dev = [
    "prek>=0.4.14",
    "ruff>=0.16.3,<0.17.0"
]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = [
    "ASYNC",  # async calls that do not await anything or use blocking methods
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "COM8",  # flake8-commas linter
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "FA102",  # future annotations
    "I",  # isort
    "N",  # PEP8 naming conventions
    "PTH",  # use pathlib instead of os
    "Q",  # flake8-quotes
    "RUF",  # RUF specific fixes
    "T20",  # flake8-print
    "TC",  # flake8-type-checking
    "TID",  # flake8-tidy-imports
    "UP",  # pyupgrade
    "W"  # pycodestyle warnings
]
extend-safe-fixes = [
    "TC"  # move import from and to TYPE_CHECKING blocks
]
ignore = [
    "COM812",  # missing-trailing-comma
    "E501",  # suppress line-too-long, let formatter decide
    "N806"  # uppercase variables in functions
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.tomlsort]
all = true
ignore_case = true
in_place = true
sort_first = ["name", "project", "select", "version"]
spaces_before_inline_comment = 2
spaces_indent_inline_array = 4
